### ISSUE TITLE
Default username and password for Openshift install

### ISSUE THREAD

**Issue by dirkgomez** [keycloak/server_installation_guide#13]
According to the installation document there is no default user on an Openshift install. Is that so? 

How am I able to create an initial admin user? Or is there one?

**Comment by dirkgomez** [comment]
OK, here's what I did:

I ran:

`rhc setup`

to properly setup my rhc console.

I then logged onto the console with 
`rhc ssh <appname>`, e.g.:
`rhc ssh keycloak`, e.g.:

And then ran:

`
env | grep OPENSHIFT_KEYCLOAK_USERNAME
env | grep OPENSHIFT_KEYCLOAK_PASSWORD
`

**Comment by stianst** [comment]
This is not the correct place to report issues. Please try the user mailing list first, then use JIRA to report issues. You can find the required links on our website.
